### ISSUE TITLE
Support Vector 5.1 community edition

### ISSUE THREAD

**Issue by monda07** [ActianCorp/Vector-Community-Docker#5]
The DockerFile has hardcoded Vector 5.0 and now that 5.1 is out, this seems misleading.  Remove the specific version stamps since the installers are compatible.
Also, fix the tarball file expression to handle the situation where the full installer has the current relevant patch number embedded

**Comment by monda07** [comment]
Fixed by Pull Request #6

**Comment by clach04** [comment]
Resolved by issue #6.
@monda07 only just spotted this, it is worth including the issue number in the commit message /pull request so that GitHub auto links. I'm this manually so this I think we are good now 😄
